#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Setup Terraform backend infrastructure (S3 + DynamoDB) in LocalStack
.DESCRIPTION
    This script creates the necessary S3 bucket and DynamoDB table for 
    Terraform remote state management in LocalStack
.PARAMETER Environment
    Environment name (develop, nonprod, etc.)
.PARAMETER LocalstackEndpoint
    LocalStack endpoint URL
.EXAMPLE
    .\setup_backend.ps1 -Environment develop
.EXAMPLE
    .\setup_backend.ps1 -Environment develop -LocalstackEndpoint http://localhost:4566
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$Environment,
    
    [Parameter(Mandatory=$false)]
    [string]$LocalstackEndpoint = "http://localhost:4566"
)

$ErrorActionPreference = "Stop"

Write-Host "🔧 Setting up Terraform backend for environment: $Environment" -ForegroundColor Green

# Check if LocalStack is running
try {
    $response = Invoke-RestMethod -Uri "$LocalstackEndpoint/_localstack/health" -TimeoutSec 5
    Write-Host "✅ LocalStack is running" -ForegroundColor Green
} catch {
    Write-Error "❌ LocalStack is not running at $LocalstackEndpoint"
    Write-Error "   Please start LocalStack first: .\scripts\run_localstack_env.ps1 -env $Environment"
    exit 1
}

# Set working directory to backend
$backendDir = Join-Path $PSScriptRoot "../backend"
Push-Location $backendDir

try {
    Write-Host "📁 Working in: $(Get-Location)" -ForegroundColor Cyan
    
    # Create backend.auto.tfvars for this environment
    $backendVarsPath = "backend.$Environment.auto.tfvars"
    $backendVarsContent = @"
state_bucket_name   = "terraform-state-$Environment"
lock_table_name     = "terraform-locks-$Environment"
localstack_endpoint = "$LocalstackEndpoint"
"@
    
    Write-Host "📝 Creating $backendVarsPath" -ForegroundColor Yellow
    $backendVarsContent | Out-File -FilePath $backendVarsPath -Encoding UTF8
    
    # Initialize Terraform
    Write-Host "🔄 Initializing Terraform..." -ForegroundColor Yellow
    terraform init
    
    # Plan the backend infrastructure
    Write-Host "📋 Planning backend infrastructure..." -ForegroundColor Yellow
    terraform plan -var-file="$backendVarsPath" -out="backend-$Environment.tfplan"
    
    # Apply the backend infrastructure
    Write-Host "🚀 Creating backend infrastructure..." -ForegroundColor Yellow
    terraform apply "backend-$Environment.tfplan"
    
    # Get outputs
    Write-Host "📊 Getting backend configuration..." -ForegroundColor Yellow
    $backendConfig = terraform output -json backend_config | ConvertFrom-Json
    
    # Generate backend configuration file for environments
    $envBackendConfigPath = "../environments/backend-$Environment.tf"
    $backendConfigContent = @"
# Backend configuration for $Environment environment
# Generated by setup_backend.ps1

terraform {
  backend "s3" {
    bucket         = "$($backendConfig.bucket)"
    key            = "$Environment/terraform.tfstate"
    region         = "$($backendConfig.region)"
    dynamodb_table = "$($backendConfig.dynamodb_table)"
    encrypt        = true
    
    # LocalStack specific settings
    endpoint                    = "$($backendConfig.endpoint)"
    access_key                  = "$($backendConfig.access_key)"
    secret_key                  = "$($backendConfig.secret_key)"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    s3_use_path_style          = true
  }
}
"@
    
    Write-Host "📝 Creating backend configuration: $envBackendConfigPath" -ForegroundColor Yellow
    $backendConfigContent | Out-File -FilePath $envBackendConfigPath -Encoding UTF8
    
    Write-Host ""
    Write-Host "🎉 Backend setup complete!" -ForegroundColor Green
    Write-Host "📁 State bucket: $($backendConfig.bucket)" -ForegroundColor Cyan
    Write-Host "🔒 Lock table: $($backendConfig.dynamodb_table)" -ForegroundColor Cyan
    Write-Host "📄 Backend config created: $envBackendConfigPath" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "🔄 To use the backend, run:" -ForegroundColor Yellow
    Write-Host "   cd ../environments" -ForegroundColor Gray
    Write-Host "   terraform init -reconfigure" -ForegroundColor Gray
    
} catch {
    Write-Error "❌ Failed to setup backend: $($_.Exception.Message)"
    exit 1
} finally {
    Pop-Location
}