#!/bin/bash
set -e

# Setup Terraform backend infrastructure (S3 + DynamoDB) in LocalStack
# This script creates the necessary S3 bucket and DynamoDB table for 
# Terraform remote state management in LocalStack

ENVIRONMENT=""
LOCALSTACK_ENDPOINT="http://localhost:4566"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -e|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        -l|--localstack-endpoint)
            LOCALSTACK_ENDPOINT="$2"
            shift 2
            ;;
        -h|--help)
            echo "Usage: $0 -e|--environment ENVIRONMENT [-l|--localstack-endpoint ENDPOINT]"
            echo "Example: $0 -e develop"
            exit 0
            ;;
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done

if [ -z "$ENVIRONMENT" ]; then
    echo "❌ Environment is required"
    echo "Usage: $0 -e|--environment ENVIRONMENT"
    exit 1
fi

echo "🔧 Setting up Terraform backend for environment: $ENVIRONMENT"

# Check if LocalStack is running
if ! curl -f "$LOCALSTACK_ENDPOINT/_localstack/health" &> /dev/null; then
    echo "❌ LocalStack is not running at $LOCALSTACK_ENDPOINT"
    echo "   Please start LocalStack first: ./scripts/run_localstack_env.sh -e $ENVIRONMENT"
    exit 1
fi

echo "✅ LocalStack is running"

# Set working directory to backend
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$SCRIPT_DIR/../../backend"
cd "$BACKEND_DIR"

echo "📁 Working in: $(pwd)"

# Create backend.auto.tfvars for this environment
BACKEND_VARS_PATH="backend.$ENVIRONMENT.auto.tfvars"
cat > "$BACKEND_VARS_PATH" << EOF
state_bucket_name   = "terraform-state-$ENVIRONMENT"
lock_table_name     = "terraform-locks-$ENVIRONMENT"
localstack_endpoint = "$LOCALSTACK_ENDPOINT"
EOF

echo "📝 Created $BACKEND_VARS_PATH"

# Initialize Terraform
echo "🔄 Initializing Terraform..."
terraform init

# Plan the backend infrastructure
echo "📋 Planning backend infrastructure..."
terraform plan -var-file="$BACKEND_VARS_PATH" -out="backend-$ENVIRONMENT.tfplan"

# Apply the backend infrastructure
echo "🚀 Creating backend infrastructure..."
terraform apply "backend-$ENVIRONMENT.tfplan"

# Get outputs
echo "📊 Getting backend configuration..."
BUCKET=$(terraform output -raw state_bucket_name)
LOCK_TABLE=$(terraform output -raw lock_table_name)
REGION="us-east-1"
ENDPOINT="http://localhost:4566"
ACCESS_KEY="test"
SECRET_KEY="test"

# Generate backend configuration file for environments
ENV_BACKEND_CONFIG_PATH="../environments/backend-$ENVIRONMENT.tf"
cat > "$ENV_BACKEND_CONFIG_PATH" << EOF
# Backend configuration for $ENVIRONMENT environment
# Generated by setup_backend.sh

terraform {
  backend "s3" {
    bucket         = "$BUCKET"
    key            = "$ENVIRONMENT/terraform.tfstate"
    region         = "$REGION"
    dynamodb_table = "$LOCK_TABLE"
    encrypt        = true
    
    # LocalStack specific settings
    endpoint                    = "$ENDPOINT"
    access_key                  = "$ACCESS_KEY"
    secret_key                  = "$SECRET_KEY"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_requesting_account_id  = true
    s3_use_path_style          = true
  }
}
EOF

echo ""
echo "🎉 Backend setup complete!"
echo "📁 State bucket: $BUCKET"
echo "🔒 Lock table: $LOCK_TABLE"
echo "📄 Backend config created: $ENV_BACKEND_CONFIG_PATH"
echo ""
echo "🔄 To use the backend, run:"
echo "   cd ../environments"
echo "   terraform init -reconfigure"